### ISSUE TITLE
indentation issue

### ISSUE THREAD

**Issue by mattanimation** [tcosolutions/betterscan#191]
Steps to reproduce:
- cloned git repo
- cd to dockerhub folder
- ran `docker compose up` (with docker desktop running)
- after containers are downloaded I am met with the follow error 

```
worker_1-1  | Traceback (most recent call last):
worker_1-1  |   File "/srv/betterscan/manage.py", line 22, in <module>
worker_1-1  |     from quantifiedcode.settings import settings
worker_1-1  |   File "/srv/betterscan/quantifiedcode/settings/__init__.py", line 22, in <module>
worker_1-1  |     from .base import * #noqa
worker_1-1  |   File "/srv/betterscan/quantifiedcode/settings/base.py", line 33, in <module>
worker_1-1  |     from quantifiedcode.helpers.settings import Settings, load_settings
worker_1-1  |   File "/srv/betterscan/quantifiedcode/helpers/settings.py", line 34, in <module>
worker_1-1  |     from checkmate.settings import Settings as CheckmateSettings
worker_1-1  |   File "/usr/local/lib/python3.8/site-packages/checkmate/settings/__init__.py", line 1, in <module>
worker_1-1  |     from .base import *
worker_1-1  |   File "/usr/local/lib/python3.8/site-packages/checkmate/settings/base.py", line 11, in <module>
worker_1-1  |     from . import defaults
worker_1-1  |   File "/usr/local/lib/python3.8/site-packages/checkmate/settings/defaults.py", line 67
worker_1-1  |     language_patterns = {
worker_1-1  |     ^
worker_1-1  | IndentationError: unexpected indent
```

**Comment by marcinguy** [comment]
Cleaned it up and removed some patters (of languages/tech not anymore supported)

**Comment by marcinguy** [comment]
The issue you saw I did not have. However I have this issue for a longer, no idea why. `pyyaml` is installed

both in server and worker

```
**server-1    |     import yaml
server-1    | ModuleNotFoundError: No module named 'yaml'**
```
