### ISSUE TITLE
NameError: name 'Backend' is not defined Checkmate

### ISSUE THREAD

**Issue by akhashimov** [tcosolutions/betterscan#209]
Hello,

when I ran the following:
`docker run --rm -v /code:/code --env CODE_DIR=/code sunsolution/betterscan-worker-cli:latest sh -c "cd /code && checkmate init && checkmate git init && checkmate git analyze"`
I got the following error:
```
/root
/code
/code
Loading plugin: git
Loading plugin: bandit
Loading plugin: brakeman
Loading plugin: tfsec
Loading plugin: kubescape
Loading plugin: semgrepjava
Loading plugin: semgrepeslint
Loading plugin: graudit
Loading plugin: text4shell
Loading plugin: gostaticcheck
Loading plugin: gptanalyzer
Traceback (most recent call last):
  File "/usr/local/bin/checkmate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/checkmate/scripts/manage.py", line 90, in main
    backend = get_backend(project_path, project_config, settings)
  File "/usr/local/lib/python3.8/site-packages/checkmate/management/helpers.py", line 100, in get_backend
    backend = Backend()  # Default backend class if unrecognized backend_type
NameError: name 'Backend' is not defined
```

Can you help me out ?

**Comment by akhashimov** [comment]
Sorry, found the following script to better understand how to use:
https://raw.githubusercontent.com/tcosolutions/betterscan-ce/main/cli.sh
Also in readme there's a description about backend:
https://github.com/tcosolutions/betterscan?tab=readme-ov-file#1-binary-runtime
