### ISSUE TITLE
run "cli.sh" failed

### ISSUE THREAD

**Issue by yuFeiCode** [tcosolutions/betterscan#210]
**### ubutun-18.04 and i run the following command:**
```
sh <(curl https://raw.githubusercontent.com/tcosolutions/betterscan-ce/main/cli.sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   943  100   943    0     0   1827      0 --:--:-- --:--:-- --:--:--  1827
```

**### finally i got this error:**
```
/root
/home/zhouyufei/test/test-file
Loading plugin: git
Loading plugin: bandit
Loading plugin: brakeman
Loading plugin: tfsec
Loading plugin: kubescape
Loading plugin: semgrepjava
Loading plugin: semgrepeslint
Loading plugin: graudit
Loading plugin: text4shell
Loading plugin: gostaticcheck
Loading plugin: gptanalyzer
Initializing new project in the current directory.
Project initialized with sqlite backend at /home/zhouyufei/test/test-file

/root
/home/zhouyufei/test/test-file
/home/zhouyufei/test/test-file
Loading plugin: git
Loading plugin: bandit
Loading plugin: brakeman
Loading plugin: tfsec
Loading plugin: kubescape
Loading plugin: semgrepjava
Loading plugin: semgrepeslint
Loading plugin: graudit
Loading plugin: text4shell
Loading plugin: gostaticcheck
Loading plugin: gptanalyzer
Traceback (most recent call last):
  File "/usr/local/bin/checkmate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/checkmate/scripts/manage.py", line 90, in main
    backend = get_backend(project_path, project_config, settings)
  File "/usr/local/lib/python3.8/site-packages/checkmate/management/helpers.py", line 105, in get_backend
    backend.create_tables()
AttributeError: 'FileBackend' object has no attribute 'create_tables'
```
Could you help me figure out what's wrong in here?

**Comment by marcinguy** [comment]
@yuFeiCode please try it now

**Comment by yuFeiCode** [comment]
@marcinguy i try again and i got same error:
```
/root
/home/zhouyufei/test/test-file
/home/zhouyufei/test/test-file
Loading plugin: git
Loading plugin: bandit
Loading plugin: brakeman
Loading plugin: tfsec
Loading plugin: kubescape
Loading plugin: semgrepjava
Loading plugin: semgrepeslint
Loading plugin: graudit
Loading plugin: text4shell
Loading plugin: gostaticcheck
Loading plugin: gptanalyzer
Traceback (most recent call last):
  File "/usr/local/bin/checkmate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/checkmate/scripts/manage.py", line 90, in main
    backend = get_backend(project_path, project_config, settings)
  File "/usr/local/lib/python3.8/site-packages/checkmate/management/helpers.py", line 105, in get_backend
    backend.create_tables()
AttributeError: 'FileBackend' object has no attribute 'create_tables'
```

**Comment by marcinguy** [comment]
@yuFeiCode rebuilt now. Please try again

**Comment by yuFeiCode** [comment]
@marcinguy thanks for you help, but i got the same error too.
Still report
```
zhouyufei@DESKTOP-OKOTLBJ:~/test/test-file$ sh <(curl https://raw.githubusercontent.com/tcosolutions/betterscan-ce/main/cli.sh)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   943  100   943    0     0   1989      0 --:--:-- --:--:-- --:--:--  1985
/root
/home/zhouyufei/test/test-file
Loading plugin: git
Loading plugin: bandit
Loading plugin: brakeman
Loading plugin: tfsec
Loading plugin: kubescape
Loading plugin: semgrepjava
Loading plugin: semgrepeslint
Loading plugin: graudit
Loading plugin: text4shell
Loading plugin: gostaticcheck
Loading plugin: gptanalyzer
Initializing new project in the current directory.
Project initialized with sqlite backend at /home/zhouyufei/test/test-file
/root
/home/zhouyufei/test/test-file
/home/zhouyufei/test/test-file
Loading plugin: git
Loading plugin: bandit
Loading plugin: brakeman
Loading plugin: tfsec
Loading plugin: kubescape
Loading plugin: semgrepjava
Loading plugin: semgrepeslint
Loading plugin: graudit
Loading plugin: text4shell
Loading plugin: gostaticcheck
Loading plugin: gptanalyzer
Traceback (most recent call last):
  File "/usr/local/bin/checkmate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/checkmate/scripts/manage.py", line 90, in main
    backend = get_backend(project_path, project_config, settings)
  File "/usr/local/lib/python3.8/site-packages/checkmate/management/helpers.py", line 105, in get_backend
    backend.create_tables()
AttributeError: 'FileBackend' object has no attribute 'create_tables'
/root
/home/zhouyufei/test/test-file
/home/zhouyufei/test/test-file
Loading plugin: git
Loading plugin: bandit
Loading plugin: brakeman
Loading plugin: tfsec
Loading plugin: kubescape
Loading plugin: semgrepjava
Loading plugin: semgrepeslint
Loading plugin: graudit
Loading plugin: text4shell
Loading plugin: gostaticcheck
Loading plugin: gptanalyzer
Traceback (most recent call last):
  File "/usr/local/bin/checkmate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/checkmate/scripts/manage.py", line 90, in main
    backend = get_backend(project_path, project_config, settings)
  File "/usr/local/lib/python3.8/site-packages/checkmate/management/helpers.py", line 105, in get_backend
    backend.create_tables()
AttributeError: 'FileBackend' object has no attribute 'create_tables'
/root
/home/zhouyufei/test/test-file
/home/zhouyufei/test/test-file
Loading plugin: git
Loading plugin: bandit
Loading plugin: brakeman
Loading plugin: tfsec
Loading plugin: kubescape
Loading plugin: semgrepjava
Loading plugin: semgrepeslint
Loading plugin: graudit
Loading plugin: text4shell
Loading plugin: gostaticcheck
Loading plugin: gptanalyzer
Traceback (most recent call last):
  File "/usr/local/bin/checkmate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/checkmate/scripts/manage.py", line 90, in main
    backend = get_backend(project_path, project_config, settings)
  File "/usr/local/lib/python3.8/site-packages/checkmate/management/helpers.py", line 105, in get_backend
    backend.create_tables()
AttributeError: 'FileBackend' object has no attribute 'create_tables'
```

**Comment by yuFeiCode** [comment]
@marcinguy  About six months ago, I successfully downloaded the Docker image "tcosolutions/betterscan-ce:worker-cli" from Docker Desktop. This image was quite large at 9.8GB. However, when I try to search for this image in Docker Desktop now, I can't find it anymore. By the way, six months ago I successfully ran betterscan-ce on this image.

**Comment by marcinguy** [comment]
@yuFeiCode since six months ago many things changed (new repository setup, GitHub organization etc relicense, adding proper licensing info ,clean up of code, removal of some checkers to ensure Open Source compliance)

I did some adjustments to build other components via CICD like checkmate (the working horse underneath) and publish to pypi via gh action

please try now

**Comment by marcinguy** [comment]
Please reopen when needed

**Comment by yuFeiCode** [comment]
@marcinguy I'm trying to manually build Betterscan-ce from Docker. After executing the command:
 `checkmate init --backend sqlite --backend-opts \"sqlite:////${CODE_DIR}/.checkmate/database.db\"`
theoretically, there should be a **database.db** file in the **.checkmate** folder. However, although the checkmate init command shows successful execution, there's no **database.db** file in the **.checkmate** directory. Note that I'm using the checkmate version that comes with the Docker image and haven't changed its version. **Is this because of a version issue or something else?**
```
zhouyufei@DESKTOP-OKOTLBJ:~$ cd test
zhouyufei@DESKTOP-OKOTLBJ:~/test$ ls -la
total 88
drwxr-xr-x  3 zhouyufei zhouyufei 4096 Dec 14 10:38 .
drwxr-xr-x 23 zhouyufei zhouyufei 4096 Dec 12 17:46 ..
drwxr-xr-x  7 zhouyufei zhouyufei 4096 Dec 12 17:46 .git
-rw-r--r--  1 zhouyufei zhouyufei 6991 Sep  4  2023 contrib_analyzers_common_src_java_org_apache_lucene_analysis_ar_ArabicAnalyzer.java
-rw-r--r--  1 zhouyufei zhouyufei 8334 Sep  4  2023 contrib_analyzers_common_src_java_org_apache_lucene_analysis_br_BrazilianAnalyzer.java
-rw-r--r--  1 zhouyufei zhouyufei 4974 Sep  4  2023 contrib_analyzers_common_src_java_org_apache_lucene_analysis_cjk_CJKAnalyzer.java
-rw-r--r--  1 zhouyufei zhouyufei 7865 Sep  4  2023 contrib_analyzers_common_src_java_org_apache_lucene_analysis_cjk_CJKTokenizer.java
-rw-r--r--  1 zhouyufei zhouyufei 2739 Sep  4  2023 contrib_analyzers_common_src_java_org_apache_lucene_analysis_cn_ChineseFilter.java
-rw-r--r--  1 zhouyufei zhouyufei 3995 Sep  4  2023
zhouyufei@DESKTOP-OKOTLBJ:~/test$ export CODE_DIR=${PWD}
zhouyufei@DESKTOP-OKOTLBJ:~/test$ docker run -e CODE_DIR=$CODE_DIR -e OPENAI_GPT_API -v ${CODE_DIR}:${CODE_DIR} -ti tcosolutions/betterscan-worker-cli:latest /bin/sh
# cd $CODE_DIR
# ls
contrib_analyzers_common_src_java_org_apache_lucene_analysis_ar_ArabicAnalyzer.java
contrib_analyzers_common_src_java_org_apache_lucene_analysis_br_BrazilianAnalyzer.java
contrib_analyzers_common_src_java_org_apache_lucene_analysis_cjk_CJKAnalyzer.java
contrib_analyzers_common_src_java_org_apache_lucene_analysis_cjk_CJKTokenizer.java
contrib_analyzers_common_src_java_org_apache_lucene_analysis_cn_ChineseFilter.java
contrib_analyzers_common_src_java_org_apache_lucene_analysis_cn_ChineseTokenizer.java
contrib_analyzers_common_src_java_org_apache_lucene_analysis_compound_CompoundWordTokenFilterBase.java
contrib_analyzers_common_src_java_org_apache_lucene_analysis_compound_DictionaryCompoundWordTokenFilter.java
contrib_analyzers_common_src_java_org_apache_lucene_analysis_compound_HyphenationCompoundWordTokenFilter.java
contrib_analyzers_common_src_java_org_apache_lucene_analysis_cz_CzechAnalyzer.java
# git config --global --add safe.directory $CODE_DIR
# checkmate init --backend sqlite --backend-opts \"sqlite:////${CODE_DIR}/.checkmate/database.db\"
/root
/home/zhouyufei/test
Loading plugin: git
Loading plugin: bandit
Loading plugin: brakeman
Loading plugin: tfsec
Loading plugin: kubescape
Loading plugin: semgrepjava
Loading plugin: semgrepeslint
Loading plugin: graudit
Loading plugin: text4shell
Loading plugin: gostaticcheck
Loading plugin: gptanalyzer
Initializing new project in the current directory.
Project initialized with sqlite backend at /home/zhouyufei/test
# pip list
Package           Version
----------------- -------
blitzdb5          4.0.20
checkmate5        4.0.101
greenlet          3.1.1
pip               24.3.1
PyYAML            6.0.2
setuptools        57.5.0
SQLAlchemy        2.0.36
typing_extensions 4.12.2
wheel             0.44.0

# cd .checkmate
# ls
config.json
# cat config.json
{"project_id": "302991ccb4d8461c86411c341004ab44", "project_class": "Project", "backend": {"driver": "sql", "connection_string": "postgresql://user:password@localhost/mydatabase"}}# 
```

**Comment by yuFeiCode** [comment]
@marcinguy  when the **checkmate init** command shows successful execution. Than i try:
`checkmate git init --backend sqlite --backend-opts \"sqlite:////${CODE_DIR}/.checkmate/database.db\"`
It still report the same error, i don't know why:
```
/root
/home/zhouyufei/test
/home/zhouyufei/test
Loading plugin: git
Loading plugin: bandit
Loading plugin: brakeman
Loading plugin: tfsec
Loading plugin: kubescape
Loading plugin: semgrepjava
Loading plugin: semgrepeslint
Loading plugin: graudit
Loading plugin: text4shell
Loading plugin: gostaticcheck
Loading plugin: gptanalyzer
Traceback (most recent call last):
  File "/usr/local/bin/checkmate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/checkmate/scripts/manage.py", line 90, in main
    backend = get_backend(project_path, project_config, settings)
  File "/usr/local/lib/python3.8/site-packages/checkmate/management/helpers.py", line 105, in get_backend
    backend.create_tables()
AttributeError: 'SQLBackend' object has no attribute 'create_tables'
```
